---
# Simple Hello World playbook
# This is the most basic Ansible playbook example
# Run with: ansible-playbook playbooks/hello-world.yml -i inventory/localhost

- name: Hello World Demo
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Print a simple message
      debug:
        msg: "Hello, World! Welcome to Ansible!"

    - name: Show current date and time
      debug:
        msg: "Current date and time: {{ ansible_date_time.iso8601 }}"

    - name: Display Ansible version
      debug:
        msg: "Running Ansible version {{ ansible_version.full }}"

    - name: Show system information
      debug:
        msg: |
          Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Hostname: {{ ansible_hostname }}
          Architecture: {{ ansible_architecture }}
