---
# Webserver role - handlers
# Handlers are triggered by 'notify' in tasks

- name: restart webserver
  service:
    name: "{{ web_service }}"
    state: restarted

- name: reload webserver
  service:
    name: "{{ web_service }}"
    state: reloaded
