---
# Webserver role - main tasks
# This role installs and configures a basic web server

- name: Install web server package
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install web server package (RedHat)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Create web root directory
  file:
    path: "{{ web_root }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'

- name: Deploy index page from template
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0644'
  notify: restart webserver

- name: Ensure web server is started and enabled
  service:
    name: "{{ web_service }}"
    state: started
    enabled: yes
