---
# Playbook using the webserver role
# Run with: ansible-playbook playbooks/use-role.yml -i inventory/localhost
# Note: This requires sudo privileges

- name: Deploy Webserver using Role
  hosts: localhost
  become: yes
  gather_facts: yes

  roles:
    - webserver

  post_tasks:
    - name: Display completion message
      debug:
        msg: "Webserver has been deployed successfully!"
